-- 코드를 입력하세요
SELECT DISTINCT YEAR(SALES_DATE) AS YEAR, 
        MONTH(SALES_DATE) AS MONTH, 
        GENDER,  
        COUNT(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO a, ONLINE_SALE b
WHERE a.USER_ID = b.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;